export const ADD_ITEM = 'ADD_ITEM'
export const SORT_ITEM = 'SORT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_IMG_BLUR = 'UPDATE_IMG_BLUR'
export const UPDATE_IMG_GRAYSCALE = 'UPDATE_IMG_GRAYSCALE'
export const UPDATE_IMG_CONTRAST = 'UPDATE_IMG_CONTRAST'


